=== MosesTroyer/BlastSearcher/bin/libraries/jobo.dtd
<!ELEMENT JoBo ( Robot? | 
                 URLCheck? | 
                 DownloadRuleSet? |
                 LocalizeLinks? |
                 StoreCGI )  >

<!ELEMENT Robot ( AgentName? | 
                  StartReferer? | 
                  IgnoreRobotsTxt? |
                  SleepTime? |
                  MaxDepth? |
                  WalkToOtherHosts? |
                  Proxy? |
		  Bandwidth? |
                  MaxAge? |
                  EnableCookies |
                  AllowWholeHost? |
                  AllowWholeDomain? |
                  FlexibleHostCheck? |
                  AllowCaching? |
		  AllowedURL* |
		  VisitMany* |
		  FormHandler*
		  )?  >

<!ELEMENT URLCheck ( RegExpRule* )?  >

<!ATTLIST URLCheck
           default CDATA #IMPLIED >

<!ELEMENT DownloadRuleSet ( DownloadRule* ) >

<!ATTLIST DownloadRuleSet
           default CDATA #IMPLIED >

<!ELEMENT AgentName (#PCDATA)* >

<!ELEMENT StartReferer (#PCDATA)* >

<!ELEMENT IgnoreRobotsTxt (#PCDATA)* >

<!ELEMENT SleepTime (#PCDATA)* >

<!ELEMENT MaxDepth (#PCDATA)* >

<!ELEMENT WalkToOtherHosts (#PCDATA)* >

<!ELEMENT Proxy (#PCDATA)* >

<!ELEMENT AllowWholeHost (#PCDATA)* >

<!ELEMENT AllowWholeDomain (#PCDATA)* >

<!ELEMENT AllowCaching (#PCDATA)* >

<!ELEMENT FlexibleHostCheck (#PCDATA)* >

<!ELEMENT AllowedURL (#PCDATA)* >

<!ELEMENT VisitMany (#PCDATA)* >

<!ELEMENT Bandwidth (#PCDATA)* >

<!ELEMENT FormHandler ( FormField* ) >

<!ATTLIST FormHandler 
           url CDATA #REQUIRED >

<!ELEMENT FormField EMPTY >

<!ATTLIST FormField
           name CDATA #REQUIRED
	   value CDATA #REQUIRED >

<!ELEMENT RegExpRule EMPTY >

<!ATTLIST RegExpRule 
           allow CDATA #REQUIRED
           pattern CDATA  #REQUIRED >

<!ELEMENT DownloadRule EMPTY >

<!ATTLIST DownloadRule 
           allow CDATA #REQUIRED
           minSize CDATA #IMPLIED 
           maxSize CDATA #IMPLIED 
           mimeType CDATA #REQUIRED >

<!ELEMENT LocalizeLinks ( #PCDATA ) >

<!ELEMENT StoreCGI ( #PCDATA ) >

=== MosesTroyer/BlastSearcher/bin/libraries/jobo.xml
<?xml version="1.0"?>

<!DOCTYPE JoBo SYSTEM "jobo.dtd">

<JoBo>

 <Robot>
  <!--  <AgentName>JoBo (http://www.matuschek.net/jobo.html)</AgentName> -->
  <StartReferer>http://www.matuschek.net/jobo.html</StartReferer>
  <IgnoreRobotsTxt>false</IgnoreRobotsTxt>
  <SleepTime>5</SleepTime>
  <MaxDepth>2</MaxDepth>
  <WalkToOtherHosts>false</WalkToOtherHosts>
  <Bandwidth>0</Bandwidth>
  <!-- <MaxDocumentAge>30</MaxDocumentAge> -->
  <AllowWholeHost>true</AllowWholeHost>
  <AllowWholeDomain>false</AllowWholeDomain>
  <AllowCaching>true</AllowCaching>  
  <FlexibleHostCheck>false</FlexibleHostCheck>

  <!-- Proxy configuration <Proxy>proxy.myprovider.com:80</Proxy>  -->


  <!-- robot is allowed to visit these URLs more then once -->
  <!-- (useful for forms with different parameter sets     -->
  <VisitMany>http://www.matuschek.net</VisitMany>


  <!-- form handler -->
  <FormHandler url="http://www.matuschek.net/cgi-bin/test-cgi">
   <FormField name="i" value="1"/>
   <FormField name="j" value="2"/>
   <FormField name="k" value="3"/>
  </FormHandler>
 </Robot>

 <DownloadRuleSet>
   <DownloadRule allow="true" mimeType="*/*"/>
 </DownloadRuleSet>

 <URLCheck>
   <RegExpRule allow="true" pattern="." />
 </URLCheck>

 <LocalizeLinks>false</LocalizeLinks>
 <StoreCGI>true</StoreCGI>

</JoBo>
